image: archlinux
sources:
  - https://git.sr.ht/~tcarrio/git-mirror
environment:
  PROJECT_DIR: RSonic-Unpacker
  GIT_TARGET_REPO: git@github.com:GeffDev/RSonic-Unpacker.git
secrets:
  - 4ab7eaca-6522-4ba2-a9fd-36603573dd59
tasks:
  - mirror-all: git-mirror/git-mirror.sh $PROJECT_DIR
